######################################################################
# Automatically generated by qmake (3.0) ter mai 19 22:50:28 2015
######################################################################

TEMPLATE = app
TARGET = compiler
INCLUDEPATH += .

CONFIG += c++14

# Input
HEADERS += AsmGenerator.h QuotedWord.h TokenProcessor.h
SOURCES += AsmGenerator.cpp main.cpp TokenProcessor.cpp
